### ISSUE TITLE
Connexion au site

### ISSUE THREAD

**Issue by rvallet** [rvallet/ocp12-neighborhood-app#2]
En tant qu'utilisateur, 
Je souhaite pouvoir créer un compte et m'identifier sur le site afin d'accéder à des services qui me sont propres (gestion du profil et autres fonctionnalités)

**Comment by daoudi5** [comment]
Hello tu peux ecrire au format:
<En tant que> rôle, utilisateur
<Je Veux> besoin, action
<Afin de> bénéfice, valeur métier
